name: weather_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.0-266.8.beta <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
#  get: 4.6.3
  dio: ^4.0.4
  shared_preferences: ^2.0.12
  cached_network_image: ^3.2.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.2
  build_runner: ^2.1.10
  flutter_easyloading: ^3.0.3
  page_view_indicators: ^2.0.0
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
       - asset: assets/fonts/Poppins-Bold.ttf

